FROM alpine:3.22

RUN apk add php \
        php-mysqli \
        php-mbstring \
        php-curl \
        php-fpm \
        php-json \
        php-xml \
        php-openssl \
        php-zip \
        php-gd \
        php-session \
        php-tokenizer \
        php-iconv \
        php-phar \
        wget \
        mariadb-client